### ISSUE TITLE
[RFC] Remove MUI

### ISSUE THREAD

**Issue by lkostrowski** [saleor/macaw-ui#157]
After several discussion we have some reasons to remove MUI from Macaw.

I keep this issue open to evaluate:
1. How important it is for us (how much this dependency is blocking us)
2. How much time it will take to remove it
3. What can we use instead (headless libraries?)
4. What strategy can we use for migration

**Comment by Cloud11PL** [comment]
Macaw has only a few components that were customized to match our needs. The rest of components (inputs, cards etc.) that we use in eg. Dashboard, app-template are imported directly from MUI with just some styles applied (correct me if I'm wrong though). Removing MUI would require us to re-create *all* of the components that we use, animations, and a lot of the logic behind them eg. dialogs, formcontrol etc. Therefore it's not an easy task. 

Headless libraries such as radix seems like a good option but they require quite a bit of boilerplate as they use compound components pattern. On top of that we would have to re-write all `makeStyles` styles to use stitches if applicable.

**Comment by lkostrowski** [comment]
Indeed it's not an easy task. We definitely need to consider many factors.

Maintaining a design system isn't easy, so I would try something light with not much dependencies. Headless UI's promise here seems to fit us. Also, Tailwind approach can be good to speed up development and allow some customizations. Headless UI will work it https://headlessui.com/

On one side, this isn't easy, but on the other, the longer we wait, the harder it will be.

The good part is that we don't aim to build extensible library for everyone (like MUI or Chakra), but to have consisten UI for our internal needs and for Dashboard apps.

Strategically we can consider v1 developed in parallel and slowly deprecation of v0.x

Let's wait for some comments from @saleor/frontend

**Comment by dominik-zeglen** [comment]
I planned to switch to [Material UI Base](https://mui.com/base/getting-started/overview/) to minimize required amount of work and just rewrite component styles (and markup probably). We can even keep JSS as styling engine to avoid rewriting 796 (xD) `useStyles` hooks.

**Comment by lkostrowski** [comment]
Another proposal, low-ui component foundation to be considered
https://reach.tech/
