### ISSUE TITLE
Implement Checkbox

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/macaw-ui#233]
### What I'm trying to achieve

I want to have a Checkbox with the new MacawUI design based on Figma.

### Describe a proposed solution

We should implement the `Checkbox` component based on Figma designs. It should be accessible so we could use [Radix Checkbox](https://www.radix-ui.com/docs/primitives/components/checkbox) for that.

We should also check the current Dashboard for MUI Checkbox usage and add the missing API

### Acceptance criteria
- [ ] Implement new checkboxes according to the design
- [ ] Each checkbox must state indicators along with variants:
  - variant: error, states: disabled, focused, etc.
  - variant: neutral, states: disabled, focused, etc.
- [ ] Prepare a proper storybook story that presents all of the checkboxes
- [ ] Please use references only for the token (no hardcoded colors/sizes)

Note: remember about labels

### Screenshots or mockups

![Image](https://user-images.githubusercontent.com/9116238/216948699-eb28cc43-2d5f-4362-b45d-4deda0487d7e.jpg)

**Comment by Droniu** [comment]
Fixed in #274. For migration in the dashboard there will be another issue.
