### ISSUE TITLE
Implement Rich Text input component

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/macaw-ui#302]
### What I'm trying to achieve

I want to have rich text input component in new MacawUI

### Screenshots or mockups

![CleanShot 2023-03-15 at 09 41 23@2x](https://user-images.githubusercontent.com/9116238/225254025-ebccd4cb-dc94-4d2c-8f4a-0cdfbebadf99.jpg)

**Comment by patrys** [comment]
Please also consider adding a full-screen mode to this widget (similar to how the data grid behaves)
