### ISSUE TITLE
[RFC]: Selects value API changes

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/macaw-ui#512]
### Short description of the feature

Change `Select`, `Multiselect`, and `Combobox` component API to accept value as `Option | string` instead of just `Option`.

#### Context 
Due to changes in #459 we introduced breaking changes for `Select`, `Multiselect` and `Combobox` components. Previously those components accept `string` as `value` and it was MacawUI's responsibility of finding selected options by value. After https://github.com/saleor/macaw-ui/releases/tag/v0.8.0-pre.99 we shifted this responsibility to application developers by allowing only `Option` to be passed as `value`. 

#### Proposed changes
* `Select`, `Multiselect`, and `Comobobox` components will take `Option | string` as a value so we both support old flows and new use cases

#### Summary of changes to `value`
| Before | Now | After RFC |
| ------- | ------- | ------- |
| `string` | `{label: string, value: string }` | `{label: string, value: string} or string` |

**Comment by mmiszy** [comment]
What's the benefit of using `{label: string, value: string}` instead of just `value: string` all the time?

**Comment by mmiszy** [comment]
Also, it's unclear to my how the values are compared now. Does the `value` need to the reference to one of the objects from `options`, or do you internally compare by `value.value` field?

In other words: does it work?

```tsx
<Select 
  value={{label: 'label-1', value: 'value-1'}}
  options={[{label: 'label-1', value: 'value-1'}]} 
/>
```

or do I have to do this?

```tsx
const options = [{label: 'label-1', value: 'value-1'}];

<Select 
  value={options[0]}
  options={options} 
/>
```
