### ISSUE TITLE
Bug: Adjust paddings for multiselects

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/macaw-ui#566]
### What are you trying to achieve?

I wanted to have the same padding from top and bottom (6px)

![image](https://github.com/saleor/macaw-ui/assets/9116238/65768934-c4d2-4ca2-88fd-ea9e311027ba)

### Steps to reproduce the problem

Go to Multiselect component https://macaw-ui-next.vercel.app/?path=/docs/components-multiselect--docs

### What did you expect to happen?

Padding should be the same from bottom and top - 6px

### Environment

Browser and version: Chrome
OS and version: MacOS 13.4.1

**Comment by timuric** [comment]
Label for multi select is not vertically aligned, see the difference with component above
![image](https://github.com/saleor/macaw-ui/assets/4006792/2f0a1b64-84ce-4874-bbca-bf8702d18a3f)
