### ISSUE TITLE
[RFC]: Remove size variants

### ISSUE THREAD

**Issue by timuric** [saleor/macaw-ui#575]
### Short description of the feature

- Most components come in 3 sizes, which creates visual fragmentation of the UI
- Having many choices adds more decision-making friction

### Full description

Design to be provided here

### Acceptance Criteria

- [] Reduce amount of sizes
- [] Provide clear evidence that size variations are necessary if any are kept
- [] Provide some examples of proposed changes

**Comment by lkostrowski** [comment]
Agree on my side. At apps we almost never use any size other than the default one.

Lets first establish higher level patterns and learn on them. If we have actual need for sizing, we can discuss it separately (like `<Table dense>`, which is specific for table and not exactly size)
